### PR TITLE
Add support for keyboard shortcuts

### LINKED ISSUE #51: Add keyboard shortcuts for plots
### Summary

Having keyboard shortcuts throughout Rica would make changing components and their classification much easier and faster.

### Next Steps

- [ ] Research how keyboard shortcuts can be added to a React app.
- [ ] Add shortcut for changing selected component.
- [ ] Add shortcut for changing classification.

### PR DESCRIPTION
**Pull request by eurunuela**
Closes #51 

This PR adds support for keyboard shortcuts to accept (a), reject (r) and ignore (i) components, as well as to move left and right on the plots.

### CODE REVIEW

**Comment by dowdlelt** [comment]
I'm going to try and test this, but I have a feeling I may request a slight change based on ergonomics. (a)ccept and (r)eject work well, but if I'm cycling through components with the arrow keys, the (i)gnore is in an inconvenient location. maybe i(g)nore would be preferable? 

let me actually try it though and see what happens.

**Comment by jbteves** [comment]
Keep in mind that when decision tree modularization is merged, "ignored" won't be an option.

**Comment by dowdlelt** [comment]
After testing, huge fan. its really quick to go through things and relabeling specific components seemed to work correctly when I check the new classification file. Just did 175 components very swiftly. 

I can see a future with more keyboard shortcuts (Shift+a - jump to first accepted, ']' to go over a 'page', etc) but I don't think that needs to be here now. 

also this is the first time I have used RICA and it worked great, so kudos. It even played nice when I decided to try and pull the tedana folder from a mounted server location.

**Comment by eurunuela** [comment]
> I can see a future with more keyboard shortcuts (Shift+a - jump to first accepted, ']' to go over a 'page', etc) but I don't think that needs to be here now. 

I have these in mind for whenever the decision tree changes happen. I'm expecting these changes to add some complexity to Rica, so I want to see how it all comes together first.

**Comment by eurunuela** [comment]
I have only received positive feedback re: this PR. I will merge the changes.

**Pull request merged**
